// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY9uR5rSLkIXCCp0HiZY06_U9UqwCZY-w',
    appId: '1:976236341866:web:686d4a88d9cd3ebe19b813',
    messagingSenderId: '976236341866',
    projectId: 'mobiluygulama-8aefa',
    authDomain: 'mobiluygulama-8aefa.firebaseapp.com',
    storageBucket: 'mobiluygulama-8aefa.appspot.com',
    measurementId: 'G-TP525S5YMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvsEdzGNfrFum4dcyDKaB6absNDjfvxWw',
    appId: '1:976236341866:android:c1adbd2238f12f1d19b813',
    messagingSenderId: '976236341866',
    projectId: 'mobiluygulama-8aefa',
    storageBucket: 'mobiluygulama-8aefa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf3Lb1YBartY3cuHEwZolePU7sR0OzJ9Y',
    appId: '1:976236341866:ios:5186eba840c7a5fc19b813',
    messagingSenderId: '976236341866',
    projectId: 'mobiluygulama-8aefa',
    storageBucket: 'mobiluygulama-8aefa.appspot.com',
    iosBundleId: 'com.example.ayseAtesKutuphaneYonetimi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf3Lb1YBartY3cuHEwZolePU7sR0OzJ9Y',
    appId: '1:976236341866:ios:657e60e3dc4e152419b813',
    messagingSenderId: '976236341866',
    projectId: 'mobiluygulama-8aefa',
    storageBucket: 'mobiluygulama-8aefa.appspot.com',
    iosBundleId: 'com.example.ayseAtesKutuphaneYonetimi.RunnerTests',
  );
}
